var songs_dict_nice_id = {
        "L'uomo cattivo - <i>Claudio Chieffo</i>":"luomo_cattivo_claudio_chieffo",
    "Adeste, fidelis - <i>Canto popular (atribuido a D João IV)</i>":"adeste_fidelis_canto_popular_atribuido_a_d_joao_iv",
    "El Ebro guarda silencio - <i>(Francisco García de Val)</i>":"el_ebro_guarda_silencio_francisco_garcia_de_val",
    "En el portal de Belén":"en_el_portal_de_belen",
    "Avé Maria":"ave_maria",
    "O Rouxinol - <i>Tradicional Alentejo</i>":"o_rouxinol_tradicional_alentejo",
    "Então porque não, porque não - <i>Alentejo</i>":"entao_porque_nao_porque_nao_alentejo",
    "Hoy cantaré":"hoy_cantare",
    "Resce la Lune":"resce_la_lune",
    "A estrada da montanha - <i>Madredeus</i>":"a_estrada_da_montanha_madredeus",
    "Vinde, Senhor":"vinde_senhor",
    "Vero amor è Gesù":"vero_amor_e_gesu",
    "Cremos em Vós - <i>L. Mason</i>":"cremos_em_vos_l_mason",
    "Early in the morning - <i>Peter, Paul and Mary</i>":"early_in_the_morning_peter_paul_and_mary",
    "Ballata dell’ amore vero - <i>Claudio Chieffo</i>":"ballata_dell_amore_vero_claudio_chieffo",
    "Restolho - <i>Mafalda Veiga</i>":"restolho_mafalda_veiga",
    "Il mio volto - <i>Adriana Mascagni</i>":"il_mio_volto_adriana_mascagni",
    "Hino da redenção - <i>A. Marani</i>":"hino_da_redencao_a_marani",
    "Polorum Regina - <i>Llivre Vermell de Montserrat, séc. XIV</i>":"polorum_regina_llivre_vermell_de_montserrat_sec_xiv",
    "I still haven’t found - <i>U2</i>":"i_still_havent_found_u2",
    "Bendito sejas Senhor - <i>A. Cartageno</i>":"bendito_sejas_senhor_a_cartageno",
    "Senta-te Aí - <i>Rio Grande</i>":"sentate_ai_rio_grande",
    "Rainha da Paz - <i>Claudio Chieffo, Rafael Andreo, Paulino Carrascosa Jimenez</i>":"rainha_da_paz_claudio_chieffo_rafael_andreo_paulino_carrascosa_jimenez",
    "L’iniziativa - <i>Claudio Chieffo</i>":"liniziativa_claudio_chieffo",
    "Camminerò - <i>Alberto Marani</i>":"camminero_alberto_marani",
    "Avé Maria - <i>Paul Décha / Miguel Carneiro</i>":"ave_maria_paul_decha__miguel_carneiro",
    "Jesus Cristo ontem e hoje - <i>A. Cartageno</i>":"jesus_cristo_ontem_e_hoje_a_cartageno",
    "In questa notte splendida - <i>Claudio Chieffo</i>":"in_questa_notte_splendida_claudio_chieffo",
    "O corpo de Jesus é alimento - <i>A. Cartageno</i>":"o_corpo_de_jesus_e_alimento_a_cartageno",
    "All My Trials - <i>Peter, Paul and Mary</i>":"all_my_trials_peter_paul_and_mary",
    "Ave, generosa - <i>Gregoriano (Hildegard von Bingen)</i>":"ave_generosa_gregoriano_hildegard_von_bingen",
    "O dolcezza - <i>Anónimo / F. J. Haydn</i>":"o_dolcezza_anonimo__f_j_haydn",
    "Freedom":"freedom",
    "Perdoa-me Senhor - <i>Claudio Chieffo</i>":"perdoame_senhor_claudio_chieffo",
    "O dolce casa mia - <i>Anónimo</i>":"o_dolce_casa_mia_anonimo",
    "Maria Isabel":"maria_isabel",
    "Mo ghile mear “our hero” - <i>Popular Irlandesa</i>":"mo_ghile_mear_our_hero_popular_irlandesa",
    "Manto de Açucenas - <i>Maria Manuel Cid/Custódio Castelo</i>":"manto_de_acucenas_maria_manuel_cidcustodio_castelo",
    "Maravilhas":"maravilhas",
    "Na sua dor os homens encontraram":"na_sua_dor_os_homens_encontraram",
    "Dá-me uma pinguinha d’água - <i>Baixo Alentejo</i>":"dame_uma_pinguinha_dagua_baixo_alentejo",
    "Novo coração - <i>Frei Hermano da Câmara</i>":"novo_coracao_frei_hermano_da_camara",
    "Gloria":"gloria",
    "Rorate caeli desuper - <i>Hino - Tempo de Advento</i>":"rorate_caeli_desuper_hino__tempo_de_advento",
    "Teach Me To Know - <i>The Lone Bellow</i>":"teach_me_to_know_the_lone_bellow",
    "Pod Tvoju milost’ - <i>Dimitrij Bortnjanskij</i>":"pod_tvoju_milost_dimitrij_bortnjanskij",
    "Ballata dell’uomo vecchio - <i>Claudio chieffo</i>":"ballata_delluomo_vecchio_claudio_chieffo",
    "Pai nosso - <i>F. Melro / M. Luis</i>":"pai_nosso_f_melro__m_luis",
    "Settle down - <i>Peter, Paul and Mary</i>":"settle_down_peter_paul_and_mary",
    "Mi sei scoppiato dentro al cuore":"mi_sei_scoppiato_dentro_al_cuore",
    "Vós que fostes baptizados":"vos_que_fostes_baptizados",
    "Feliz és Tu - <i>C. Silva</i>":"feliz_es_tu_c_silva",
    "Haja o que houver - <i>Madredeus</i>":"haja_o_que_houver_madredeus",
    "Ó grande alegria - <i>G. F. Haendel</i>":"o_grande_alegria_g_f_haendel",
    "Victimae Paschali - <i>Sequência - Tempo Pascal</i>":"victimae_paschali_sequencia__tempo_pascal",
    "O sanctissima - <i>Canto siciliano</i>":"o_sanctissima_canto_siciliano",
    "Os olhos da Marianita - <i>Popular</i>":"os_olhos_da_marianita_popular",
    "Forever young - <i>Bob Dylan</i>":"forever_young_bob_dylan",
    "Foi Deus - <i>Amália Rodrigues</i>":"foi_deus_amalia_rodrigues",
    "Give me Jesus":"give_me_jesus",
    "O menino está dormindo":"o_menino_esta_dormindo",
    "Vent fin - <i>Música tradicional francesa</i>":"vent_fin_musica_tradicional_francesa",
    "Vós sereis meus amigos":"vos_sereis_meus_amigos",
    "Ser poeta - <i>Florbela Espanca, L. Represas</i>":"ser_poeta_florbela_espanca_l_represas",
    "Stabat Mater - <i>Jacopone da Todi</i>":"stabat_mater_jacopone_da_todi",
    "Romaria - <i>Renato Teixeira</i>":"romaria_renato_teixeira",
    "Salelaka Mokonzi - <i>Congo</i>":"salelaka_mokonzi_congo",
    "Parce Domine - <i>Gregoriano</i>":"parce_domine_gregoriano",
    "Romaria Das Festas de Santa Eufémia - <i>Miguel Araújo</i>":"romaria_das_festas_de_santa_eufemia_miguel_araujo",
    "Sol ponte, sol que morre - <i>Maria Teresa de Noronha</i>":"sol_ponte_sol_que_morre_maria_teresa_de_noronha",
    "Sul pajon - <i>Canto Alpino</i>":"sul_pajon_canto_alpino",
    "Aria di neve - <i>Adriana Mascagni</i>":"aria_di_neve_adriana_mascagni",
    "Te Deum - <i>Gregoriano</i>":"te_deum_gregoriano",
    "Razón de Vivir - <i>Mercedes Sosa</i>":"razon_de_vivir_mercedes_sosa",
    "Pater mi - <i>Anónimo</i>":"pater_mi_anonimo",
    "Regina Caeli - <i>Antífona - Tempo Pascal</i>":"regina_caeli_antifona__tempo_pascal",
    "Bendizemos o Teu nome - <i>Claudio Chieffo</i>":"bendizemos_o_teu_nome_claudio_chieffo",
    "Povera voce - <i>Adriana Mascagni</i>":"povera_voce_adriana_mascagni",
    "La Virgen de Guadalupe - <i>Popular sul-americana</i>":"la_virgen_de_guadalupe_popular_sulamericana",
    "O pão - <i>Tradução rítmica</i>":"o_pao_traducao_ritmica",
    "Preghiera a Maria - <i>Daniele Semprini</i>":"preghiera_a_maria_daniele_semprini",
    "The wind in the willows":"the_wind_in_the_willows",
    "A Tua Vinda - <i>Simplus</i>":"a_tua_vinda_simplus",
    "Do fundo do Abismo - <i>M. Buztler</i>":"do_fundo_do_abismo_m_buztler",
    "Santa Bárbara - <i>Popular asturiana</i>":"santa_barbara_popular_asturiana",
    "Sub tuum praesidium - <i>Gregoriano</i>":"sub_tuum_praesidium_gregoriano",
    "Avé Maria, estrela da manhã - <i>Adriana Mascagni</i>":"ave_maria_estrela_da_manha_adriana_mascagni",
    "Negra Sombra":"negra_sombra",
    "Facing west - <i>The Staves</i>":"facing_west_the_staves",
    "Formamos um só Corpo - <i>C. Silva</i>":"formamos_um_so_corpo_c_silva",
    "Ave Regina coelorum - <i>Gregoriano</i>":"ave_regina_coelorum_gregoriano",
    "Junto de Ti":"junto_de_ti",
    "Ognun m’entenda - <i>Códice Ven. Marciana, séc. XV</i>":"ognun_mentenda_codice_ven_marciana_sec_xv",
    "Di più - <i>Claudio Chieffo</i>":"di_piu_claudio_chieffo",
    "Olhei para o céu - <i>Elvas</i>":"olhei_para_o_ceu_elvas",
    "Vitória! Tu reinarás!":"vitoria_tu_reinaras",
    "Serrana mia":"serrana_mia",
    "Os Céus - <i>Claudio Chieffo - Tradução Ritmica</i>":"os_ceus_claudio_chieffo__traducao_ritmica",
    "Eres alta y delgada":"eres_alta_y_delgada",
    "Canzone di San Giuseppe":"canzone_di_san_giuseppe",
    "Stava a’ pie’ della croce":"stava_a_pie_della_croce",
    "Nossa Senhora, Mãe de Jesus":"nossa_senhora_mae_de_jesus",
    "Il seme - <i>Claudio Chieffo</i>":"il_seme_claudio_chieffo",
    "Gaudete - <i>Piae Cantiones, séc. XVI</i>":"gaudete_piae_cantiones_sec_xvi",
    "Guardai-me junto de vós - <i>M. Luis</i>":"guardaime_junto_de_vos_m_luis",
    "Senhora nossa":"senhora_nossa",
    "Luntane, cchiù luntane - <i>Popular abrucesa, Itália</i>":"luntane_cchiu_luntane_popular_abrucesa_italia",
    "Che siano una sola cosa - <i>Roberto Grotti</i>":"che_siano_una_sola_cosa_roberto_grotti",
    "Senhor, Nosso Deus - <i>P. Molino</i>":"senhor_nosso_deus_p_molino",
    "Salve, Mater misericordiae - <i>J. Pothier, séc. XIX</i>":"salve_mater_misericordiae_j_pothier_sec_xix",
    "Seigneur où es-Tu - <i>A M Cocagnac (O.P.)</i>":"seigneur_ou_estu_a_m_cocagnac_op",
    "All Night, All Day - <i>Bay Ridge Band</i>":"all_night_all_day_bay_ridge_band",
    "Vieux pèlerin - <i>A.-Z. Serrand</i>":"vieux_pelerin_az_serrand",
    "Ao romper da bela aurora - <i>Alentejo</i>":"ao_romper_da_bela_aurora_alentejo",
    "O amor de Deus repousa em mim - <i>M. Luis</i>":"o_amor_de_deus_repousa_em_mim_m_luis",
    "Tomai, Senhor e recebei":"tomai_senhor_e_recebei",
    "Uma estrela se foi pôr":"uma_estrela_se_foi_por",
    "Vamos lá saindo - <i>Baixo Alentejo</i>":"vamos_la_saindo_baixo_alentejo",
    "Swing low, sweet chariot - <i>Espiritual Negro</i>":"swing_low_sweet_chariot_espiritual_negro",
    "Prosternimus preces - <i>Gregoriano</i>":"prosternimus_preces_gregoriano",
    "Cuando de mi Patrona":"cuando_de_mi_patrona",
    "Tinta verde - <i>Popular portuguesa</i>":"tinta_verde_popular_portuguesa",
    "Jesu tibi vivo":"jesu_tibi_vivo",
    "A minha alma tem sede do Deus vivo (Salmo 41) - <i>J. Gelineau e D. Stefani</i>":"a_minha_alma_tem_sede_do_deus_vivo_salmo_41_j_gelineau_e_d_stefani",
    "Omne homo ad alta voce - <i>Laudário de Cortona, sec. XIII</i>":"omne_homo_ad_alta_voce_laudario_de_cortona_sec_xiii",
    "Postal dos Correios - <i>Rio Grande</i>":"postal_dos_correios_rio_grande",
    "As Mondadeiras - <i>Tradicional Alentejo</i>":"as_mondadeiras_tradicional_alentejo",
    "Destinos que Deus nos deu - <i>Teresa Tarouca</i>":"destinos_que_deus_nos_deu_teresa_tarouca",
    "Comei do pão":"comei_do_pao",
    "La guerra - <i>Claudio Chieffo</i>":"la_guerra_claudio_chieffo",
    "Magnificat - <i>Monjas Trapistas de Vitorchiano / C. Silva</i>":"magnificat_monjas_trapistas_de_vitorchiano__c_silva",
    "Vento":"vento",
    "Lauda, Sion, Salvatorem - <i>Gregoriano</i>":"lauda_sion_salvatorem_gregoriano",
    "Nazareth Morning - <i>Bay Ridge Band</i>":"nazareth_morning_bay_ridge_band",
    "Favola - <i>Claudio Chieffo</i>":"favola_claudio_chieffo",
    "Christus vincit - <i>Tradicional (melodia: A. Kunc)</i>":"christus_vincit_tradicional_melodia_a_kunc",
    "E verrà - <i>Parole e musica di Claudio Chieffo</i>":"e_verra_parole_e_musica_di_claudio_chieffo",
    "Non c'è nessuno - <i>Adriana Mascagni</i>":"non_ce_nessuno_adriana_mascagni",
    "Valsa do vai não vás - <i>António Zambujo</i>":"valsa_do_vai_nao_vas_antonio_zambujo",
    "Voi ch’amate lo Criatore - <i>Laudário de Cortona, séc. XIII</i>":"voi_chamate_lo_criatore_laudario_de_cortona_sec_xiii",
    "Senhora, nós Vos louvamos":"senhora_nos_vos_louvamos",
    "Foste, foste - <i>Popular portuguesa (Alentejo)</i>":"foste_foste_popular_portuguesa_alentejo",
    "Omni die - <i>Antífona</i>":"omni_die_antifona",
    "Rock my soul - <i>Espiritual Negro</i>":"rock_my_soul_espiritual_negro",
    "Está o nosso olhar voltado para o Senhor (Salmo 122) - <i>V. Cazzaniga/J. Gelineau</i>":"esta_o_nosso_olhar_voltado_para_o_senhor_salmo_122_v_cazzanigaj_gelineau",
    "Como é grande - <i>Roberto Grotti – Tradução Rítmica</i>":"como_e_grande_roberto_grotti__traducao_ritmica",
    "Senhora, um dia descestes":"senhora_um_dia_descestes",
    "Io non sono degno - <i>Claudio Chieffo</i>":"io_non_sono_degno_claudio_chieffo",
    "Canzone degli occhi e del cuore - <i>Claudio Chieffo</i>":"canzone_degli_occhi_e_del_cuore_claudio_chieffo",
    "Awake My Soul - <i>Mumford & Sons</i>":"awake_my_soul_mumford__sons",
    "Dispiasi’ d’noi autri povri alpin - <i>Tradicinal piemontesa</i>":"dispiasi_dnoi_autri_povri_alpin_tradicinal_piemontesa",
    "Attende Domine - <i>Hino - Tempo de Quaresma</i>":"attende_domine_hino__tempo_de_quaresma",
    "Vuestra soy - <i>S. Teresa de Ávila / Canto Venezuelano</i>":"vuestra_soy_s_teresa_de_avila__canto_venezuelano",
    "The Cave - <i>Mumford & Sons</i>":"the_cave_mumford__sons",
    "Il monologo di Giuda - <i>Claudio Chieffo</i>":"il_monologo_di_giuda_claudio_chieffo",
    "Come and go with me - <i>Bay Ridge Band</i>":"come_and_go_with_me_bay_ridge_band",
    "Vamos todos":"vamos_todos",
    "Mare di Grazia - <i>Adriana Mascagni</i>":"mare_di_grazia_adriana_mascagni",
    "Both sides of the tweed - <i>Mary Black</i>":"both_sides_of_the_tweed_mary_black",
    "Ma non avere paura - <i>Claudio Chieffo</i>":"ma_non_avere_paura_claudio_chieffo",
    "Inno delle scolte d’Assisi - <i>Canto Alpino</i>":"inno_delle_scolte_dassisi_canto_alpino",
    "Away in a Manger":"away_in_a_manger",
    "Grão de trigo":"grao_de_trigo",
    "Salve Regina - <i>Antífona</i>":"salve_regina_antifona",
    "O pão que o teu amor nos dá - <i>C. Silva</i>":"o_pao_que_o_teu_amor_nos_da_c_silva",
    "Il mistero - <i>Antonio Sicari, Gianni Bracchi</i>":"il_mistero_antonio_sicari_gianni_bracchi",
    "Compadre já te casaste? - <i>Alentejo</i>":"compadre_ja_te_casaste_alentejo",
    "Grazie, Signore - <i>Adriana Mascagni</i>":"grazie_signore_adriana_mascagni",
    "Hero - <i>Family of the Year</i>":"hero_family_of_the_year",
    "Agnus Dei":"agnus_dei",
    "Non Nobis":"non_nobis",
    "Como busca el tierno Infante - <i>Canção venezuelana</i>":"como_busca_el_tierno_infante_cancao_venezuelana",
    "O Jesu mi dulcissime":"o_jesu_mi_dulcissime",
    "Homeward Bound - <i>Simon and Garfunkel</i>":"homeward_bound_simon_and_garfunkel",
    "Este é o dia do Senhor - <i>J. A. Espinoza</i>":"este_e_o_dia_do_senhor_j_a_espinoza",
    "Natal de Elvas":"natal_de_elvas",
    "Malmequer de Santarém - <i>Tradicional Ribatejo</i>":"malmequer_de_santarem_tradicional_ribatejo",
    "Já deixei o Alentejo":"ja_deixei_o_alentejo",
    "Ai Mê Maneli - <i>Popular</i>":"ai_me_maneli_popular",
    "Apparirà - <i>A.M. Cocagnac / P. Houdy</i>":"apparira_am_cocagnac__p_houdy",
    "You":"you",
    "Quando (já nada é intacto) - <i>Mafalda Veiga</i>":"quando_ja_nada_e_intacto_mafalda_veiga",
    "Egli è il tuo bon Jesù - <i>Dionisius Placensis</i>":"egli_e_il_tuo_bon_jesu_dionisius_placensis",
    "Ó ferreiro, guarda a filha":"o_ferreiro_guarda_a_filha",
    "Chant de Pénitence - <i>A.M. Cocagnac (O.P.)</i>":"chant_de_penitence_am_cocagnac_op",
    "Ave, maris stella - <i>Hino</i>":"ave_maris_stella_hino",
    "Trago Alentejo na voz - <i>António Zambujo (?)</i>":"trago_alentejo_na_voz_antonio_zambujo_",
    "La strada - <i>Claudio Chieffo</i>":"la_strada_claudio_chieffo",
    "Todos me querem":"todos_me_querem",
    "Viva la companì":"viva_la_compani",
    "The Things that I see - <i>Bay Ridge Band</i>":"the_things_that_i_see_bay_ridge_band",
    "Il giovane ricco - <i>Claudio Chieffo</i>":"il_giovane_ricco_claudio_chieffo",
    "Zachée - <i>A. M. Cocagnac (O.P.)</i>":"zachee_a_m_cocagnac_op",
    "La traccia":"la_traccia",
    "Reina de la Paz - <i>Claudio Chieffo</i>":"reina_de_la_paz_claudio_chieffo",
    "Matérias do Coração - <i>Miguel Araújo</i>":"materias_do_coracao_miguel_araujo",
    "Faz, ó Deus":"faz_o_deus",
    "Il nostro cuore - <i>Roberto Grotti</i>":"il_nostro_cuore_roberto_grotti",
    "Sou feliz, Senhor":"sou_feliz_senhor",
    "Santa Maria, Mãe de Deus - <i>M. Simões</i>":"santa_maria_mae_de_deus_m_simoes",
    "Canção da romã - <i>Baixo Alentejo</i>":"cancao_da_roma_baixo_alentejo",
    "Descei Espírito Criador - <i>Hino - Pentecostes</i>":"descei_espirito_criador_hino__pentecostes",
    "Tenho pena lindo amor - <i>Alentejo</i>":"tenho_pena_lindo_amor_alentejo",
    "Fonte de água viva":"fonte_de_agua_viva",
    "Para que quero eu olhos - <i>Adriano Correia de Oliveira</i>":"para_que_quero_eu_olhos_adriano_correia_de_oliveira",
    "Noi non sappiamo chi era - <i>A. e G. Roscio, A. e G. Agape</i>":"noi_non_sappiamo_chi_era_a_e_g_roscio_a_e_g_agape",
    "Estranha forma de vida - <i>Alfredo Duarte, Amália Rodrigues</i>":"estranha_forma_de_vida_alfredo_duarte_amalia_rodrigues",
    "Joshua fought the battle of Jericho":"joshua_fought_the_battle_of_jericho",
    "Balada de Caridade - <i>Padre Reginaldo Manzotti</i>":"balada_de_caridade_padre_reginaldo_manzotti",
    "Miserere (Salmo 50) - <i>A. Mascagni</i>":"miserere_salmo_50_a_mascagni",
    "Ó rama, ó que linda rama - <i>Alentejo</i>":"o_rama_o_que_linda_rama_alentejo",
    "Anime affaticate et sitibonde - <i>F. Soto de Langa, séc. XVI</i>":"anime_affaticate_et_sitibonde_f_soto_de_langa_sec_xvi",
    "Ubi caritas et amor - <i>Antífona</i>":"ubi_caritas_et_amor_antifona",
    "Ho un amico - <i>Claudio Chieffo</i>":"ho_un_amico_claudio_chieffo",
    "Mattone su mattone":"mattone_su_mattone",
    "Sigh No More - <i>Mumford & Sons</i>":"sigh_no_more_mumford__sons",
    "Cheira a Lisboa":"cheira_a_lisboa",
    "Eu sou o Pão da Vida - <i>B. Sousa</i>":"eu_sou_o_pao_da_vida_b_sousa",
    "Sevillanas del adiós - <i>Sevilhana</i>":"sevillanas_del_adios_sevilhana",
    "O quam amabilis - <i>Anónimo</i>":"o_quam_amabilis_anonimo",
    "Meu coração e os olhos - <i>Popular portuguesa (Douro Litoral)</i>":"meu_coracao_e_os_olhos_popular_portuguesa_douro_litoral",
    "Where Are You Going - <i>Dave Mathews Band</i>":"where_are_you_going_dave_mathews_band",
    "Viecerni Svon":"viecerni_svon",
    "Quinta Feira da Ascenção - <i>Canto Tradicional</i>":"quinta_feira_da_ascencao_canto_tradicional",
    "Eu sou o Pão Vivo - <i>C. Silva</i>":"eu_sou_o_pao_vivo_c_silva",
    "Si no te tuviera a ti - <i>Siempre así</i>":"si_no_te_tuviera_a_ti_siempre_asi",
    "Lágrima - <i>Amália Rodrigues</i>":"lagrima_amalia_rodrigues",
    "Climbin’ up the mountains - <i>Bay Ridge Band</i>":"climbin_up_the_mountains_bay_ridge_band",
    "Laude novella - <i>Laudário de Cortona, sec. XIII</i>":"laude_novella_laudario_de_cortona_sec_xiii",
    "I cieli - <i>Claudio Chieffo</i>":"i_cieli_claudio_chieffo",
    "Lela":"lela",
    "Ceifeira - <i>Baixo Alentejo</i>":"ceifeira_baixo_alentejo",
    "La rivista dell’armamento - <i>Canto Alpino</i>":"la_rivista_dellarmamento_canto_alpino",
    "Il disegno - <i>Aberto Marani</i>":"il_disegno_aberto_marani",
    "Cântico de Zacarias - <i>Monjas Trapistas de Vitorchiano</i>":"cantico_de_zacarias_monjas_trapistas_de_vitorchiano",
    "Come, my way, my truth, my life":"come_my_way_my_truth_my_life",
    "Shosholoza - <i>Música tradicional Zulu</i>":"shosholoza_musica_tradicional_zulu",
    "Alegrem-se os Céus e a Terra":"alegremse_os_ceus_e_a_terra",
    "Down in the River to Pray - <i>Alison Krauss</i>":"down_in_the_river_to_pray_alison_krauss",
    "Se il signore non costruisce la città - <i>Giuseppe Maioli</i>":"se_il_signore_non_costruisce_la_citta_giuseppe_maioli",
    "Non son sincera - <i>Adriana Mascagni</i>":"non_son_sincera_adriana_mascagni",
    "Panis angelicus - <i>Cesar Frank</i>":"panis_angelicus_cesar_frank",
    "Carbonero":"carbonero",
    "Tenho um amor em Viana":"tenho_um_amor_em_viana",
    "Slip slidin’ away - <i>Paul Simon</i>":"slip_slidin_away_paul_simon",
    "E col cifolo del vapore - <i>Canto Alpino</i>":"e_col_cifolo_del_vapore_canto_alpino",
    "Se o Senhor não constrói a cidade - <i>Giuseppe Maioli</i>":"se_o_senhor_nao_constroi_a_cidade_giuseppe_maioli",
    "Go tell it on the mountain - <i>Bay Ridge Band</i>":"go_tell_it_on_the_mountain_bay_ridge_band",
    "New Creation - <i>Bay Ridge Band</i>":"new_creation_bay_ridge_band",
    "La serenata del soldato":"la_serenata_del_soldato",
    "Nossa Senhora do Carmo":"nossa_senhora_do_carmo",
    "La ballata del potere - <i>Claudio Chieffo</i>":"la_ballata_del_potere_claudio_chieffo",
    "Christe cunctorum - <i>Hino - Dedicação do Templo</i>":"christe_cunctorum_hino__dedicacao_do_templo",
    "Nós não sabemos quem era - <i>A. e G. Roscio, A. e G. Agape</i>":"nos_nao_sabemos_quem_era_a_e_g_roscio_a_e_g_agape",
    "Pelo toque da viola - <i>Alentejo</i>":"pelo_toque_da_viola_alentejo",
    "Il pane - <i>Stefano Pianori</i>":"il_pane_stefano_pianori",
    "Glory Hallelujah":"glory_hallelujah",
    "Adoro te devote - <i>Hino</i>":"adoro_te_devote_hino",
    "Anunciação - <i>Canção Brasileira</i>":"anunciacao_cancao_brasileira",
    "Noite feliz - <i>F. X. Gruber</i>":"noite_feliz_f_x_gruber",
    "Os que semeiam em lágrimas - <i>D. Stefani/J. Gelineau</i>":"os_que_semeiam_em_lagrimas_d_stefanij_gelineau",
    "Credo":"credo",
    "Onde há caridade e amor - <i>M. Luís</i>":"onde_ha_caridade_e_amor_m_luis",
    "Confine - <i>Letra e música de Claudio Chieffo</i>":"confine_letra_e_musica_de_claudio_chieffo",
    "Rio Mira vai cheio - <i>Odemira</i>":"rio_mira_vai_cheio_odemira",
    "Al mattino - <i>Adriana Mascagni</i>":"al_mattino_adriana_mascagni",
    "Siyahamba - <i>Música tradicional Zulu</i>":"siyahamba_musica_tradicional_zulu",
    "Oh! doux pays de Chanaan - <i>A.M. Cocagnac (O.P.)</i>":"oh_doux_pays_de_chanaan_am_cocagnac_op",
    "L’opera - <i>Claudio Chieffo</i>":"lopera_claudio_chieffo",
    "Luz terna (hino) - <i>Hino Completas / Frei Hermano da Camara</i>":"luz_terna_hino_hino_completas__frei_hermano_da_camara",
    "Veni, veni Emmanuel - <i>Zoltan Kodaly</i>":"veni_veni_emmanuel_zoltan_kodaly",
    "My Lord, what a morning":"my_lord_what_a_morning",
    "O Templo de Deus - <i>C. Silva</i>":"o_templo_de_deus_c_silva",
    "Discendi, Santo Spirito - <i>Hino - Pentecostes</i>":"discendi_santo_spirito_hino__pentecostes",
    "Vuestra soy pues me criasteis - <i>S. Teresa de Ávila / Rafael Andreo</i>":"vuestra_soy_pues_me_criasteis_s_teresa_de_avila__rafael_andreo",
    "Gracias a la vida - <i>Violeta Parra</i>":"gracias_a_la_vida_violeta_parra",
    "Vieni, Signore Gesù - <i>Trapistas de Vitorchiano</i>":"vieni_signore_gesu_trapistas_de_vitorchiano",
    "Liberazione nº 2 - <i>Claudio Chieffo</i>":"liberazione_no_2_claudio_chieffo",
    "Tu mi guardi dalla croce - <i>Atribuído a W. A. Mozart</i>":"tu_mi_guardi_dalla_croce_atribuido_a_w_a_mozart",
    "Meu São Bendito - <i>Canção brasileira</i>":"meu_sao_bendito_cancao_brasileira",
    "Sanctus":"sanctus",
    "Que este vinho e este pão":"que_este_vinho_e_este_pao",
    "Quem comer deste pão - <i>C. Silva</i>":"quem_comer_deste_pao_c_silva",
    "Dai-nos um coração - <i>A. Espinosa</i>":"dainos_um_coracao_a_espinosa",
    "Ó verdadeiro corpo do Senhor - <i>C. Silva</i>":"o_verdadeiro_corpo_do_senhor_c_silva",
    "When the Saints":"when_the_saints",
    "Flattire freeway":"flattire_freeway",
    "Errore di prospettiva - <i>Claudio Chieffo</i>":"errore_di_prospettiva_claudio_chieffo",
    "Al comando dei nostri ufficiali":"al_comando_dei_nostri_ufficiali",
    "Quando uno ha il cuore buono - <i>Claudio Chieffo</i>":"quando_uno_ha_il_cuore_buono_claudio_chieffo",
    "Venite a laudare - <i>Laudário de Cortona, séc. XIII</i>":"venite_a_laudare_laudario_de_cortona_sec_xiii",
    "Por dentro de um abraço - <i>Simplus</i>":"por_dentro_de_um_abraco_simplus",
    "Luz terna":"luz_terna",
    "Vou-me embora, vou partir - <i>Alentejo</i>":"voume_embora_vou_partir_alentejo",
    "Amare ancora - <i>Claudio Chieffo</i>":"amare_ancora_claudio_chieffo",
    "Over in the glory land":"over_in_the_glory_land",
    "Os nossos rogos aceite":"os_nossos_rogos_aceite",
    "Benedetto sia lo giorno - <i>G. Animuccia</i>":"benedetto_sia_lo_giorno_g_animuccia",
    "A procissão":"a_procissao",
    "Eu ouvi um passarinho - <i>Baixo Alentejo</i>":"eu_ouvi_um_passarinho_baixo_alentejo",
    "My Father sings to Me - <i>Bay Ridge Band</i>":"my_father_sings_to_me_bay_ridge_band",
    "The fields on Athenry - <i>Pete St. John</i>":"the_fields_on_athenry_pete_st_john",
    "Veni Sancte Spiritus - <i>Sequência - Pentecostes</i>":"veni_sancte_spiritus_sequencia__pentecostes",
    "É nossa oferta":"e_nossa_oferta",
    "Marta, Marta - <i>Claudio Chieffo</i>":"marta_marta_claudio_chieffo",
    "O Desígnio - <i>Alberto Marani</i>":"o_designio_alberto_marani",
    "Only our rivers run free - <i>The Wolfe Tones</i>":"only_our_rivers_run_free_the_wolfe_tones",
    "Salve caput cruentatum - <i>Paixão e morte do Senhor</i>":"salve_caput_cruentatum_paixao_e_morte_do_senhor",
    "Dulcis Christe - <i>Michelangelo Grancini, séc. XVII</i>":"dulcis_christe_michelangelo_grancini_sec_xvii",
    "Lasciati fare - <i>Claudio Chieffo</i>":"lasciati_fare_claudio_chieffo",
    "Toda a nossa glória - <i>M. Luis</i>":"toda_a_nossa_gloria_m_luis",
    "Ora so - <i>A. e G. Roscio, A. e G. Agape</i>":"ora_so_a_e_g_roscio_a_e_g_agape",
    "Deus fez-nos um só povo - <i>Fr. Arcílio</i>":"deus_feznos_um_so_povo_fr_arcilio",
    "Verei a bondade do Senhor (Salmo 26) - <i>J. Gelineau/E. Bosio</i>":"verei_a_bondade_do_senhor_salmo_26_j_gelineaue_bosio",
    "La ceseta de transaqua - <i>Canto alpino</i>":"la_ceseta_de_transaqua_canto_alpino",
    "O surdato ‘nnammurato":"o_surdato_nnammurato",
    "Ah! vinde todos - <i>Melodia francesa</i>":"ah_vinde_todos_melodia_francesa",
    "Si Dieu ne nous aimait pas - <i>A.M. Cocagnac (O.P.)</i>":"si_dieu_ne_nous_aimait_pas_am_cocagnac_op",
    "Ave verum - <i>Sequência</i>":"ave_verum_sequencia",
    "O cor’ soave - <i>Anónimo</i>":"o_cor_soave_anonimo",
    "Toma toda a minha vida":"toma_toda_a_minha_vida",
    "Matir’ nieba i zimli":"matir_nieba_i_zimli",
    "Ave, o Vergjine - <i>canto friulano</i>":"ave_o_vergjine_canto_friulano",
    "Altissima luce - <i>Laudário de Cortona, sec. XIII</i>":"altissima_luce_laudario_de_cortona_sec_xiii",
    "Fica mal com Deus - <i>Geraldo Vandré</i>":"fica_mal_com_deus_geraldo_vandre",
    "Minha Luz - <i>Maria Teresa de Noronha</i>":"minha_luz_maria_teresa_de_noronha",
    "Will ye go, lassie, go?":"will_ye_go_lassie_go",
    "Canção de Maria Clara - <i>Claudio Chieffo</i>":"cancao_de_maria_clara_claudio_chieffo",
    "Ó luar da meia-noite - <i>Alentejo</i>":"o_luar_da_meianoite_alentejo",
    "Podes vir":"podes_vir",
    "Cantiga do alecrim":"cantiga_do_alecrim",
    "Signore delle cime - <i>Canto Alpino</i>":"signore_delle_cime_canto_alpino",
    "Caminharei - <i>Alberto Marani – Tradução Rítmica</i>":"caminharei_alberto_marani__traducao_ritmica",
    "El vito":"el_vito",
    "Saboreai e vede como é bom o Senhor! - <i>J. Gelineau</i>":"saboreai_e_vede_como_e_bom_o_senhor_j_gelineau",
    "Andança - <i>Beth Carvalho</i>":"andanca_beth_carvalho",
    "Todo Cambia - <i>Mercedes Sosa</i>":"todo_cambia_mercedes_sosa",
    "Jesu dulcis memoria - <i>Hino - por abadessa beneditina, séc. XIV</i>":"jesu_dulcis_memoria_hino__por_abadessa_beneditina_sec_xiv",
    "Salve, nobre Padroeira":"salve_nobre_padroeira",
    "Barco Negro - <i>Amália Rodrigues</i>":"barco_negro_amalia_rodrigues",
    "O spes mea cara - <i>Anónimo medieval</i>":"o_spes_mea_cara_anonimo_medieval",
    "Puer natus - <i>Anónimo medieval</i>":"puer_natus_anonimo_medieval",
    "Avé Maria, luz clara da manhã - <i>Cláudio Chieffo</i>":"ave_maria_luz_clara_da_manha_claudio_chieffo",
    "Veni Creator Spiritus - <i>Hino - Pentecostes</i>":"veni_creator_spiritus_hino__pentecostes",
    "D’amor pane dolcissimo - <i>Stefano Varnavà / Anónimo</i>":"damor_pane_dolcissimo_stefano_varnava__anonimo",
    "Canzone dell’ideale - <i>Claudio chieffo</i>":"canzone_dellideale_claudio_chieffo",
    "Avé Maria Cheia de Graça - <i>Frei. Hermano da Câmara</i>":"ave_maria_cheia_de_graca_frei_hermano_da_camara",
    "Aconteceu - <i>Adriana Calcanhoto</i>":"aconteceu_adriana_calcanhoto",
    "I wonder":"i_wonder",
    "Quem me ensinou a nadar - <i>Canção brasileira</i>":"quem_me_ensinou_a_nadar_cancao_brasileira",
    "Cantai ao Senhor um hino novo (Salmo 97) - <i>V Cazzaniga/ J. Gelineau</i>":"cantai_ao_senhor_um_hino_novo_salmo_97_v_cazzaniga_j_gelineau",
    "Tantum ergo - <i>Gregoriano</i>":"tantum_ergo_gregoriano",
    "Crux Fidelis - <i>Hino - Sexta-Feira Santa</i>":"crux_fidelis_hino__sextafeira_santa",
    "Não quero que vás á monda":"nao_quero_que_vas_a_monda",
    "Exaudi Domine - <i>Lorenzo Perosi</i>":"exaudi_domine_lorenzo_perosi",
    "Nitida Stella - <i>Melodia checa, séc. XVIII</i>":"nitida_stella_melodia_checa_sec_xviii",
    "En que nos parecemos":"en_que_nos_parecemos",
    "Pavão":"pavao",
    "Ballata del amore vero - <i>Claudio Chieffo</i>":"ballata_del_amore_vero_claudio_chieffo",
    "Padre - <i>Claudio Chieffo</i>":"padre_claudio_chieffo",
    "The wild rover":"the_wild_rover",
    "Se me envolve a noite escura":"se_me_envolve_a_noite_escura",
    "O filii et filiae - <i>Tempo Pascal</i>":"o_filii_et_filiae_tempo_pascal",
    "Jesu! Rex admirabilis - <i>P.L. Da Palestrina, 1525? - 1594</i>":"jesu_rex_admirabilis_pl_da_palestrina_1525__1594",
    "Mi prende per la mano - <i>Anónimo</i>":"mi_prende_per_la_mano_anonimo",
    "Giesù, sommo conforto":"giesu_sommo_conforto",
    "Ave Maria - <i>Gregoriano</i>":"ave_maria_gregoriano",
    "Eu te ofereço - <i>M. Giombini</i>":"eu_te_ofereco_m_giombini",
    "Romagna mia":"romagna_mia",
    "Cielito lindo":"cielito_lindo",
    "É cantando - <i>Simplus</i>":"e_cantando_simplus",
    "Quais quais - <i>Alentejo</i>":"quais_quais_alentejo",
    "Angel dal ciel disceso - <i>G. Ancina</i>":"angel_dal_ciel_disceso_g_ancina",
    "Tomai e recebei":"tomai_e_recebei",
    "Ojos de cielo - <i>Popular argentina</i>":"ojos_de_cielo_popular_argentina",
    "Tu és um Deus fiel":"tu_es_um_deus_fiel",
    "Rosa das rosas - <i>Afonso X, séc. XIII</i>":"rosa_das_rosas_afonso_x_sec_xiii",
    "Alma redemptoris - <i>Antífona - Tempo de Advento</i>":"alma_redemptoris_antifona__tempo_de_advento",
    "Vamos confiantes (Salmo 45) - <i>C. Silva</i>":"vamos_confiantes_salmo_45_c_silva",
    "A Pedra (Salmo 117) - <i>Adriana Mascagni</i>":"a_pedra_salmo_117_adriana_mascagni",
    "Menina das tranças pretas - <i>M. Rosário, V. Câmara e L. Teixeira</i>":"menina_das_trancas_pretas_m_rosario_v_camara_e_l_teixeira",
    "Timoneiro - <i>Paulinho da Viola</i>":"timoneiro_paulinho_da_viola",
    "O bom pastor":"o_bom_pastor",
    "Eu vim para que tenham vida (Salmo 145) - <i>F. Silva</i>":"eu_vim_para_que_tenham_vida_salmo_145_f_silva",
    "Il popolo canta la sua liberazione - <i>Claudio Chieffo</i>":"il_popolo_canta_la_sua_liberazione_claudio_chieffo",
    "Menina estás à janela - <i>Vitorino</i>":"menina_estas_a_janela_vitorino",
    "Verdes são os campos - <i>Luís de Camões, José Afonso</i>":"verdes_sao_os_campos_luis_de_camoes_jose_afonso",
    "Tu sei un Dio fedele - <i>Anónimo</i>":"tu_sei_un_dio_fedele_anonimo",
    "Long time traveler - <i>The Waillin’ Jennys</i>":"long_time_traveler_the_waillin_jennys",
    "A Banda - <i>Chico Buarque</i>":"a_banda_chico_buarque",
    "Argento - <i>Claudio Chieffo</i>":"argento_claudio_chieffo",
    "A treze de Maio":"a_treze_de_maio",
    "Nella tua pace - <i>Ciro Picciano</i>":"nella_tua_pace_ciro_picciano",
    "O bone Jesu - <i>P. da Palestrina, séc. XVI</i>":"o_bone_jesu_p_da_palestrina_sec_xvi",
    "Il testamento del capitano - <i>Canto alpino</i>":"il_testamento_del_capitano_canto_alpino",
    "Quem tem sede venha a Mim - <i>Taizé</i>":"quem_tem_sede_venha_a_mim_taize",
    "Hino a São José - <i>José Antonio Poblete</i>":"hino_a_sao_jose_jose_antonio_poblete",
    "Vinde à presença do Senhor - <i>(Salmo 99) V. Cazzaniga, J. Gelineau</i>":"vinde_a_presenca_do_senhor_salmo_99_v_cazzaniga_j_gelineau",
    "Abandonei - <i>A. e G. Roscio, A. e G. Agape - tradução ritmica</i>":"abandonei_a_e_g_roscio_a_e_g_agape__traducao_ritmica",
    "Vinde e Contemplai - <i>Cartageno</i>":"vinde_e_contemplai_cartageno",

};

var songs_dict_id_nice = {
        "luomo_cattivo_claudio_chieffo":"L'uomo cattivo - <i>Claudio Chieffo</i>",
    "adeste_fidelis_canto_popular_atribuido_a_d_joao_iv":"Adeste, fidelis - <i>Canto popular (atribuido a D João IV)</i>",
    "el_ebro_guarda_silencio_francisco_garcia_de_val":"El Ebro guarda silencio - <i>(Francisco García de Val)</i>",
    "en_el_portal_de_belen":"En el portal de Belén",
    "ave_maria":"Avé Maria",
    "o_rouxinol_tradicional_alentejo":"O Rouxinol - <i>Tradicional Alentejo</i>",
    "entao_porque_nao_porque_nao_alentejo":"Então porque não, porque não - <i>Alentejo</i>",
    "hoy_cantare":"Hoy cantaré",
    "resce_la_lune":"Resce la Lune",
    "a_estrada_da_montanha_madredeus":"A estrada da montanha - <i>Madredeus</i>",
    "vinde_senhor":"Vinde, Senhor",
    "vero_amor_e_gesu":"Vero amor è Gesù",
    "cremos_em_vos_l_mason":"Cremos em Vós - <i>L. Mason</i>",
    "early_in_the_morning_peter_paul_and_mary":"Early in the morning - <i>Peter, Paul and Mary</i>",
    "ballata_dell_amore_vero_claudio_chieffo":"Ballata dell’ amore vero - <i>Claudio Chieffo</i>",
    "restolho_mafalda_veiga":"Restolho - <i>Mafalda Veiga</i>",
    "il_mio_volto_adriana_mascagni":"Il mio volto - <i>Adriana Mascagni</i>",
    "hino_da_redencao_a_marani":"Hino da redenção - <i>A. Marani</i>",
    "polorum_regina_llivre_vermell_de_montserrat_sec_xiv":"Polorum Regina - <i>Llivre Vermell de Montserrat, séc. XIV</i>",
    "i_still_havent_found_u2":"I still haven’t found - <i>U2</i>",
    "bendito_sejas_senhor_a_cartageno":"Bendito sejas Senhor - <i>A. Cartageno</i>",
    "sentate_ai_rio_grande":"Senta-te Aí - <i>Rio Grande</i>",
    "rainha_da_paz_claudio_chieffo_rafael_andreo_paulino_carrascosa_jimenez":"Rainha da Paz - <i>Claudio Chieffo, Rafael Andreo, Paulino Carrascosa Jimenez</i>",
    "liniziativa_claudio_chieffo":"L’iniziativa - <i>Claudio Chieffo</i>",
    "camminero_alberto_marani":"Camminerò - <i>Alberto Marani</i>",
    "ave_maria_paul_decha__miguel_carneiro":"Avé Maria - <i>Paul Décha / Miguel Carneiro</i>",
    "jesus_cristo_ontem_e_hoje_a_cartageno":"Jesus Cristo ontem e hoje - <i>A. Cartageno</i>",
    "in_questa_notte_splendida_claudio_chieffo":"In questa notte splendida - <i>Claudio Chieffo</i>",
    "o_corpo_de_jesus_e_alimento_a_cartageno":"O corpo de Jesus é alimento - <i>A. Cartageno</i>",
    "all_my_trials_peter_paul_and_mary":"All My Trials - <i>Peter, Paul and Mary</i>",
    "ave_generosa_gregoriano_hildegard_von_bingen":"Ave, generosa - <i>Gregoriano (Hildegard von Bingen)</i>",
    "o_dolcezza_anonimo__f_j_haydn":"O dolcezza - <i>Anónimo / F. J. Haydn</i>",
    "freedom":"Freedom",
    "perdoame_senhor_claudio_chieffo":"Perdoa-me Senhor - <i>Claudio Chieffo</i>",
    "o_dolce_casa_mia_anonimo":"O dolce casa mia - <i>Anónimo</i>",
    "maria_isabel":"Maria Isabel",
    "mo_ghile_mear_our_hero_popular_irlandesa":"Mo ghile mear “our hero” - <i>Popular Irlandesa</i>",
    "manto_de_acucenas_maria_manuel_cidcustodio_castelo":"Manto de Açucenas - <i>Maria Manuel Cid/Custódio Castelo</i>",
    "maravilhas":"Maravilhas",
    "na_sua_dor_os_homens_encontraram":"Na sua dor os homens encontraram",
    "dame_uma_pinguinha_dagua_baixo_alentejo":"Dá-me uma pinguinha d’água - <i>Baixo Alentejo</i>",
    "novo_coracao_frei_hermano_da_camara":"Novo coração - <i>Frei Hermano da Câmara</i>",
    "gloria":"Gloria",
    "rorate_caeli_desuper_hino__tempo_de_advento":"Rorate caeli desuper - <i>Hino - Tempo de Advento</i>",
    "teach_me_to_know_the_lone_bellow":"Teach Me To Know - <i>The Lone Bellow</i>",
    "pod_tvoju_milost_dimitrij_bortnjanskij":"Pod Tvoju milost’ - <i>Dimitrij Bortnjanskij</i>",
    "ballata_delluomo_vecchio_claudio_chieffo":"Ballata dell’uomo vecchio - <i>Claudio chieffo</i>",
    "pai_nosso_f_melro__m_luis":"Pai nosso - <i>F. Melro / M. Luis</i>",
    "settle_down_peter_paul_and_mary":"Settle down - <i>Peter, Paul and Mary</i>",
    "mi_sei_scoppiato_dentro_al_cuore":"Mi sei scoppiato dentro al cuore",
    "vos_que_fostes_baptizados":"Vós que fostes baptizados",
    "feliz_es_tu_c_silva":"Feliz és Tu - <i>C. Silva</i>",
    "haja_o_que_houver_madredeus":"Haja o que houver - <i>Madredeus</i>",
    "o_grande_alegria_g_f_haendel":"Ó grande alegria - <i>G. F. Haendel</i>",
    "victimae_paschali_sequencia__tempo_pascal":"Victimae Paschali - <i>Sequência - Tempo Pascal</i>",
    "o_sanctissima_canto_siciliano":"O sanctissima - <i>Canto siciliano</i>",
    "os_olhos_da_marianita_popular":"Os olhos da Marianita - <i>Popular</i>",
    "forever_young_bob_dylan":"Forever young - <i>Bob Dylan</i>",
    "foi_deus_amalia_rodrigues":"Foi Deus - <i>Amália Rodrigues</i>",
    "give_me_jesus":"Give me Jesus",
    "o_menino_esta_dormindo":"O menino está dormindo",
    "vent_fin_musica_tradicional_francesa":"Vent fin - <i>Música tradicional francesa</i>",
    "vos_sereis_meus_amigos":"Vós sereis meus amigos",
    "ser_poeta_florbela_espanca_l_represas":"Ser poeta - <i>Florbela Espanca, L. Represas</i>",
    "stabat_mater_jacopone_da_todi":"Stabat Mater - <i>Jacopone da Todi</i>",
    "romaria_renato_teixeira":"Romaria - <i>Renato Teixeira</i>",
    "salelaka_mokonzi_congo":"Salelaka Mokonzi - <i>Congo</i>",
    "parce_domine_gregoriano":"Parce Domine - <i>Gregoriano</i>",
    "romaria_das_festas_de_santa_eufemia_miguel_araujo":"Romaria Das Festas de Santa Eufémia - <i>Miguel Araújo</i>",
    "sol_ponte_sol_que_morre_maria_teresa_de_noronha":"Sol ponte, sol que morre - <i>Maria Teresa de Noronha</i>",
    "sul_pajon_canto_alpino":"Sul pajon - <i>Canto Alpino</i>",
    "aria_di_neve_adriana_mascagni":"Aria di neve - <i>Adriana Mascagni</i>",
    "te_deum_gregoriano":"Te Deum - <i>Gregoriano</i>",
    "razon_de_vivir_mercedes_sosa":"Razón de Vivir - <i>Mercedes Sosa</i>",
    "pater_mi_anonimo":"Pater mi - <i>Anónimo</i>",
    "regina_caeli_antifona__tempo_pascal":"Regina Caeli - <i>Antífona - Tempo Pascal</i>",
    "bendizemos_o_teu_nome_claudio_chieffo":"Bendizemos o Teu nome - <i>Claudio Chieffo</i>",
    "povera_voce_adriana_mascagni":"Povera voce - <i>Adriana Mascagni</i>",
    "la_virgen_de_guadalupe_popular_sulamericana":"La Virgen de Guadalupe - <i>Popular sul-americana</i>",
    "o_pao_traducao_ritmica":"O pão - <i>Tradução rítmica</i>",
    "preghiera_a_maria_daniele_semprini":"Preghiera a Maria - <i>Daniele Semprini</i>",
    "the_wind_in_the_willows":"The wind in the willows",
    "a_tua_vinda_simplus":"A Tua Vinda - <i>Simplus</i>",
    "do_fundo_do_abismo_m_buztler":"Do fundo do Abismo - <i>M. Buztler</i>",
    "santa_barbara_popular_asturiana":"Santa Bárbara - <i>Popular asturiana</i>",
    "sub_tuum_praesidium_gregoriano":"Sub tuum praesidium - <i>Gregoriano</i>",
    "ave_maria_estrela_da_manha_adriana_mascagni":"Avé Maria, estrela da manhã - <i>Adriana Mascagni</i>",
    "negra_sombra":"Negra Sombra",
    "facing_west_the_staves":"Facing west - <i>The Staves</i>",
    "formamos_um_so_corpo_c_silva":"Formamos um só Corpo - <i>C. Silva</i>",
    "ave_regina_coelorum_gregoriano":"Ave Regina coelorum - <i>Gregoriano</i>",
    "junto_de_ti":"Junto de Ti",
    "ognun_mentenda_codice_ven_marciana_sec_xv":"Ognun m’entenda - <i>Códice Ven. Marciana, séc. XV</i>",
    "di_piu_claudio_chieffo":"Di più - <i>Claudio Chieffo</i>",
    "olhei_para_o_ceu_elvas":"Olhei para o céu - <i>Elvas</i>",
    "vitoria_tu_reinaras":"Vitória! Tu reinarás!",
    "serrana_mia":"Serrana mia",
    "os_ceus_claudio_chieffo__traducao_ritmica":"Os Céus - <i>Claudio Chieffo - Tradução Ritmica</i>",
    "eres_alta_y_delgada":"Eres alta y delgada",
    "canzone_di_san_giuseppe":"Canzone di San Giuseppe",
    "stava_a_pie_della_croce":"Stava a’ pie’ della croce",
    "nossa_senhora_mae_de_jesus":"Nossa Senhora, Mãe de Jesus",
    "il_seme_claudio_chieffo":"Il seme - <i>Claudio Chieffo</i>",
    "gaudete_piae_cantiones_sec_xvi":"Gaudete - <i>Piae Cantiones, séc. XVI</i>",
    "guardaime_junto_de_vos_m_luis":"Guardai-me junto de vós - <i>M. Luis</i>",
    "senhora_nossa":"Senhora nossa",
    "luntane_cchiu_luntane_popular_abrucesa_italia":"Luntane, cchiù luntane - <i>Popular abrucesa, Itália</i>",
    "che_siano_una_sola_cosa_roberto_grotti":"Che siano una sola cosa - <i>Roberto Grotti</i>",
    "senhor_nosso_deus_p_molino":"Senhor, Nosso Deus - <i>P. Molino</i>",
    "salve_mater_misericordiae_j_pothier_sec_xix":"Salve, Mater misericordiae - <i>J. Pothier, séc. XIX</i>",
    "seigneur_ou_estu_a_m_cocagnac_op":"Seigneur où es-Tu - <i>A M Cocagnac (O.P.)</i>",
    "all_night_all_day_bay_ridge_band":"All Night, All Day - <i>Bay Ridge Band</i>",
    "vieux_pelerin_az_serrand":"Vieux pèlerin - <i>A.-Z. Serrand</i>",
    "ao_romper_da_bela_aurora_alentejo":"Ao romper da bela aurora - <i>Alentejo</i>",
    "o_amor_de_deus_repousa_em_mim_m_luis":"O amor de Deus repousa em mim - <i>M. Luis</i>",
    "tomai_senhor_e_recebei":"Tomai, Senhor e recebei",
    "uma_estrela_se_foi_por":"Uma estrela se foi pôr",
    "vamos_la_saindo_baixo_alentejo":"Vamos lá saindo - <i>Baixo Alentejo</i>",
    "swing_low_sweet_chariot_espiritual_negro":"Swing low, sweet chariot - <i>Espiritual Negro</i>",
    "prosternimus_preces_gregoriano":"Prosternimus preces - <i>Gregoriano</i>",
    "cuando_de_mi_patrona":"Cuando de mi Patrona",
    "tinta_verde_popular_portuguesa":"Tinta verde - <i>Popular portuguesa</i>",
    "jesu_tibi_vivo":"Jesu tibi vivo",
    "a_minha_alma_tem_sede_do_deus_vivo_salmo_41_j_gelineau_e_d_stefani":"A minha alma tem sede do Deus vivo (Salmo 41) - <i>J. Gelineau e D. Stefani</i>",
    "omne_homo_ad_alta_voce_laudario_de_cortona_sec_xiii":"Omne homo ad alta voce - <i>Laudário de Cortona, sec. XIII</i>",
    "postal_dos_correios_rio_grande":"Postal dos Correios - <i>Rio Grande</i>",
    "as_mondadeiras_tradicional_alentejo":"As Mondadeiras - <i>Tradicional Alentejo</i>",
    "destinos_que_deus_nos_deu_teresa_tarouca":"Destinos que Deus nos deu - <i>Teresa Tarouca</i>",
    "comei_do_pao":"Comei do pão",
    "la_guerra_claudio_chieffo":"La guerra - <i>Claudio Chieffo</i>",
    "magnificat_monjas_trapistas_de_vitorchiano__c_silva":"Magnificat - <i>Monjas Trapistas de Vitorchiano / C. Silva</i>",
    "vento":"Vento",
    "lauda_sion_salvatorem_gregoriano":"Lauda, Sion, Salvatorem - <i>Gregoriano</i>",
    "nazareth_morning_bay_ridge_band":"Nazareth Morning - <i>Bay Ridge Band</i>",
    "favola_claudio_chieffo":"Favola - <i>Claudio Chieffo</i>",
    "christus_vincit_tradicional_melodia_a_kunc":"Christus vincit - <i>Tradicional (melodia: A. Kunc)</i>",
    "e_verra_parole_e_musica_di_claudio_chieffo":"E verrà - <i>Parole e musica di Claudio Chieffo</i>",
    "non_ce_nessuno_adriana_mascagni":"Non c'è nessuno - <i>Adriana Mascagni</i>",
    "valsa_do_vai_nao_vas_antonio_zambujo":"Valsa do vai não vás - <i>António Zambujo</i>",
    "voi_chamate_lo_criatore_laudario_de_cortona_sec_xiii":"Voi ch’amate lo Criatore - <i>Laudário de Cortona, séc. XIII</i>",
    "senhora_nos_vos_louvamos":"Senhora, nós Vos louvamos",
    "foste_foste_popular_portuguesa_alentejo":"Foste, foste - <i>Popular portuguesa (Alentejo)</i>",
    "omni_die_antifona":"Omni die - <i>Antífona</i>",
    "rock_my_soul_espiritual_negro":"Rock my soul - <i>Espiritual Negro</i>",
    "esta_o_nosso_olhar_voltado_para_o_senhor_salmo_122_v_cazzanigaj_gelineau":"Está o nosso olhar voltado para o Senhor (Salmo 122) - <i>V. Cazzaniga/J. Gelineau</i>",
    "como_e_grande_roberto_grotti__traducao_ritmica":"Como é grande - <i>Roberto Grotti – Tradução Rítmica</i>",
    "senhora_um_dia_descestes":"Senhora, um dia descestes",
    "io_non_sono_degno_claudio_chieffo":"Io non sono degno - <i>Claudio Chieffo</i>",
    "canzone_degli_occhi_e_del_cuore_claudio_chieffo":"Canzone degli occhi e del cuore - <i>Claudio Chieffo</i>",
    "awake_my_soul_mumford__sons":"Awake My Soul - <i>Mumford & Sons</i>",
    "dispiasi_dnoi_autri_povri_alpin_tradicinal_piemontesa":"Dispiasi’ d’noi autri povri alpin - <i>Tradicinal piemontesa</i>",
    "attende_domine_hino__tempo_de_quaresma":"Attende Domine - <i>Hino - Tempo de Quaresma</i>",
    "vuestra_soy_s_teresa_de_avila__canto_venezuelano":"Vuestra soy - <i>S. Teresa de Ávila / Canto Venezuelano</i>",
    "the_cave_mumford__sons":"The Cave - <i>Mumford & Sons</i>",
    "il_monologo_di_giuda_claudio_chieffo":"Il monologo di Giuda - <i>Claudio Chieffo</i>",
    "come_and_go_with_me_bay_ridge_band":"Come and go with me - <i>Bay Ridge Band</i>",
    "vamos_todos":"Vamos todos",
    "mare_di_grazia_adriana_mascagni":"Mare di Grazia - <i>Adriana Mascagni</i>",
    "both_sides_of_the_tweed_mary_black":"Both sides of the tweed - <i>Mary Black</i>",
    "ma_non_avere_paura_claudio_chieffo":"Ma non avere paura - <i>Claudio Chieffo</i>",
    "inno_delle_scolte_dassisi_canto_alpino":"Inno delle scolte d’Assisi - <i>Canto Alpino</i>",
    "away_in_a_manger":"Away in a Manger",
    "grao_de_trigo":"Grão de trigo",
    "salve_regina_antifona":"Salve Regina - <i>Antífona</i>",
    "o_pao_que_o_teu_amor_nos_da_c_silva":"O pão que o teu amor nos dá - <i>C. Silva</i>",
    "il_mistero_antonio_sicari_gianni_bracchi":"Il mistero - <i>Antonio Sicari, Gianni Bracchi</i>",
    "compadre_ja_te_casaste_alentejo":"Compadre já te casaste? - <i>Alentejo</i>",
    "grazie_signore_adriana_mascagni":"Grazie, Signore - <i>Adriana Mascagni</i>",
    "hero_family_of_the_year":"Hero - <i>Family of the Year</i>",
    "agnus_dei":"Agnus Dei",
    "non_nobis":"Non Nobis",
    "como_busca_el_tierno_infante_cancao_venezuelana":"Como busca el tierno Infante - <i>Canção venezuelana</i>",
    "o_jesu_mi_dulcissime":"O Jesu mi dulcissime",
    "homeward_bound_simon_and_garfunkel":"Homeward Bound - <i>Simon and Garfunkel</i>",
    "este_e_o_dia_do_senhor_j_a_espinoza":"Este é o dia do Senhor - <i>J. A. Espinoza</i>",
    "natal_de_elvas":"Natal de Elvas",
    "malmequer_de_santarem_tradicional_ribatejo":"Malmequer de Santarém - <i>Tradicional Ribatejo</i>",
    "ja_deixei_o_alentejo":"Já deixei o Alentejo",
    "ai_me_maneli_popular":"Ai Mê Maneli - <i>Popular</i>",
    "apparira_am_cocagnac__p_houdy":"Apparirà - <i>A.M. Cocagnac / P. Houdy</i>",
    "you":"You",
    "quando_ja_nada_e_intacto_mafalda_veiga":"Quando (já nada é intacto) - <i>Mafalda Veiga</i>",
    "egli_e_il_tuo_bon_jesu_dionisius_placensis":"Egli è il tuo bon Jesù - <i>Dionisius Placensis</i>",
    "o_ferreiro_guarda_a_filha":"Ó ferreiro, guarda a filha",
    "chant_de_penitence_am_cocagnac_op":"Chant de Pénitence - <i>A.M. Cocagnac (O.P.)</i>",
    "ave_maris_stella_hino":"Ave, maris stella - <i>Hino</i>",
    "trago_alentejo_na_voz_antonio_zambujo_":"Trago Alentejo na voz - <i>António Zambujo (?)</i>",
    "la_strada_claudio_chieffo":"La strada - <i>Claudio Chieffo</i>",
    "todos_me_querem":"Todos me querem",
    "viva_la_compani":"Viva la companì",
    "the_things_that_i_see_bay_ridge_band":"The Things that I see - <i>Bay Ridge Band</i>",
    "il_giovane_ricco_claudio_chieffo":"Il giovane ricco - <i>Claudio Chieffo</i>",
    "zachee_a_m_cocagnac_op":"Zachée - <i>A. M. Cocagnac (O.P.)</i>",
    "la_traccia":"La traccia",
    "reina_de_la_paz_claudio_chieffo":"Reina de la Paz - <i>Claudio Chieffo</i>",
    "materias_do_coracao_miguel_araujo":"Matérias do Coração - <i>Miguel Araújo</i>",
    "faz_o_deus":"Faz, ó Deus",
    "il_nostro_cuore_roberto_grotti":"Il nostro cuore - <i>Roberto Grotti</i>",
    "sou_feliz_senhor":"Sou feliz, Senhor",
    "santa_maria_mae_de_deus_m_simoes":"Santa Maria, Mãe de Deus - <i>M. Simões</i>",
    "cancao_da_roma_baixo_alentejo":"Canção da romã - <i>Baixo Alentejo</i>",
    "descei_espirito_criador_hino__pentecostes":"Descei Espírito Criador - <i>Hino - Pentecostes</i>",
    "tenho_pena_lindo_amor_alentejo":"Tenho pena lindo amor - <i>Alentejo</i>",
    "fonte_de_agua_viva":"Fonte de água viva",
    "para_que_quero_eu_olhos_adriano_correia_de_oliveira":"Para que quero eu olhos - <i>Adriano Correia de Oliveira</i>",
    "noi_non_sappiamo_chi_era_a_e_g_roscio_a_e_g_agape":"Noi non sappiamo chi era - <i>A. e G. Roscio, A. e G. Agape</i>",
    "estranha_forma_de_vida_alfredo_duarte_amalia_rodrigues":"Estranha forma de vida - <i>Alfredo Duarte, Amália Rodrigues</i>",
    "joshua_fought_the_battle_of_jericho":"Joshua fought the battle of Jericho",
    "balada_de_caridade_padre_reginaldo_manzotti":"Balada de Caridade - <i>Padre Reginaldo Manzotti</i>",
    "miserere_salmo_50_a_mascagni":"Miserere (Salmo 50) - <i>A. Mascagni</i>",
    "o_rama_o_que_linda_rama_alentejo":"Ó rama, ó que linda rama - <i>Alentejo</i>",
    "anime_affaticate_et_sitibonde_f_soto_de_langa_sec_xvi":"Anime affaticate et sitibonde - <i>F. Soto de Langa, séc. XVI</i>",
    "ubi_caritas_et_amor_antifona":"Ubi caritas et amor - <i>Antífona</i>",
    "ho_un_amico_claudio_chieffo":"Ho un amico - <i>Claudio Chieffo</i>",
    "mattone_su_mattone":"Mattone su mattone",
    "sigh_no_more_mumford__sons":"Sigh No More - <i>Mumford & Sons</i>",
    "cheira_a_lisboa":"Cheira a Lisboa",
    "eu_sou_o_pao_da_vida_b_sousa":"Eu sou o Pão da Vida - <i>B. Sousa</i>",
    "sevillanas_del_adios_sevilhana":"Sevillanas del adiós - <i>Sevilhana</i>",
    "o_quam_amabilis_anonimo":"O quam amabilis - <i>Anónimo</i>",
    "meu_coracao_e_os_olhos_popular_portuguesa_douro_litoral":"Meu coração e os olhos - <i>Popular portuguesa (Douro Litoral)</i>",
    "where_are_you_going_dave_mathews_band":"Where Are You Going - <i>Dave Mathews Band</i>",
    "viecerni_svon":"Viecerni Svon",
    "quinta_feira_da_ascencao_canto_tradicional":"Quinta Feira da Ascenção - <i>Canto Tradicional</i>",
    "eu_sou_o_pao_vivo_c_silva":"Eu sou o Pão Vivo - <i>C. Silva</i>",
    "si_no_te_tuviera_a_ti_siempre_asi":"Si no te tuviera a ti - <i>Siempre así</i>",
    "lagrima_amalia_rodrigues":"Lágrima - <i>Amália Rodrigues</i>",
    "climbin_up_the_mountains_bay_ridge_band":"Climbin’ up the mountains - <i>Bay Ridge Band</i>",
    "laude_novella_laudario_de_cortona_sec_xiii":"Laude novella - <i>Laudário de Cortona, sec. XIII</i>",
    "i_cieli_claudio_chieffo":"I cieli - <i>Claudio Chieffo</i>",
    "lela":"Lela",
    "ceifeira_baixo_alentejo":"Ceifeira - <i>Baixo Alentejo</i>",
    "la_rivista_dellarmamento_canto_alpino":"La rivista dell’armamento - <i>Canto Alpino</i>",
    "il_disegno_aberto_marani":"Il disegno - <i>Aberto Marani</i>",
    "cantico_de_zacarias_monjas_trapistas_de_vitorchiano":"Cântico de Zacarias - <i>Monjas Trapistas de Vitorchiano</i>",
    "come_my_way_my_truth_my_life":"Come, my way, my truth, my life",
    "shosholoza_musica_tradicional_zulu":"Shosholoza - <i>Música tradicional Zulu</i>",
    "alegremse_os_ceus_e_a_terra":"Alegrem-se os Céus e a Terra",
    "down_in_the_river_to_pray_alison_krauss":"Down in the River to Pray - <i>Alison Krauss</i>",
    "se_il_signore_non_costruisce_la_citta_giuseppe_maioli":"Se il signore non costruisce la città - <i>Giuseppe Maioli</i>",
    "non_son_sincera_adriana_mascagni":"Non son sincera - <i>Adriana Mascagni</i>",
    "panis_angelicus_cesar_frank":"Panis angelicus - <i>Cesar Frank</i>",
    "carbonero":"Carbonero",
    "tenho_um_amor_em_viana":"Tenho um amor em Viana",
    "slip_slidin_away_paul_simon":"Slip slidin’ away - <i>Paul Simon</i>",
    "e_col_cifolo_del_vapore_canto_alpino":"E col cifolo del vapore - <i>Canto Alpino</i>",
    "se_o_senhor_nao_constroi_a_cidade_giuseppe_maioli":"Se o Senhor não constrói a cidade - <i>Giuseppe Maioli</i>",
    "go_tell_it_on_the_mountain_bay_ridge_band":"Go tell it on the mountain - <i>Bay Ridge Band</i>",
    "new_creation_bay_ridge_band":"New Creation - <i>Bay Ridge Band</i>",
    "la_serenata_del_soldato":"La serenata del soldato",
    "nossa_senhora_do_carmo":"Nossa Senhora do Carmo",
    "la_ballata_del_potere_claudio_chieffo":"La ballata del potere - <i>Claudio Chieffo</i>",
    "christe_cunctorum_hino__dedicacao_do_templo":"Christe cunctorum - <i>Hino - Dedicação do Templo</i>",
    "nos_nao_sabemos_quem_era_a_e_g_roscio_a_e_g_agape":"Nós não sabemos quem era - <i>A. e G. Roscio, A. e G. Agape</i>",
    "pelo_toque_da_viola_alentejo":"Pelo toque da viola - <i>Alentejo</i>",
    "il_pane_stefano_pianori":"Il pane - <i>Stefano Pianori</i>",
    "glory_hallelujah":"Glory Hallelujah",
    "adoro_te_devote_hino":"Adoro te devote - <i>Hino</i>",
    "anunciacao_cancao_brasileira":"Anunciação - <i>Canção Brasileira</i>",
    "noite_feliz_f_x_gruber":"Noite feliz - <i>F. X. Gruber</i>",
    "os_que_semeiam_em_lagrimas_d_stefanij_gelineau":"Os que semeiam em lágrimas - <i>D. Stefani/J. Gelineau</i>",
    "credo":"Credo",
    "onde_ha_caridade_e_amor_m_luis":"Onde há caridade e amor - <i>M. Luís</i>",
    "confine_letra_e_musica_de_claudio_chieffo":"Confine - <i>Letra e música de Claudio Chieffo</i>",
    "rio_mira_vai_cheio_odemira":"Rio Mira vai cheio - <i>Odemira</i>",
    "al_mattino_adriana_mascagni":"Al mattino - <i>Adriana Mascagni</i>",
    "siyahamba_musica_tradicional_zulu":"Siyahamba - <i>Música tradicional Zulu</i>",
    "oh_doux_pays_de_chanaan_am_cocagnac_op":"Oh! doux pays de Chanaan - <i>A.M. Cocagnac (O.P.)</i>",
    "lopera_claudio_chieffo":"L’opera - <i>Claudio Chieffo</i>",
    "luz_terna_hino_hino_completas__frei_hermano_da_camara":"Luz terna (hino) - <i>Hino Completas / Frei Hermano da Camara</i>",
    "veni_veni_emmanuel_zoltan_kodaly":"Veni, veni Emmanuel - <i>Zoltan Kodaly</i>",
    "my_lord_what_a_morning":"My Lord, what a morning",
    "o_templo_de_deus_c_silva":"O Templo de Deus - <i>C. Silva</i>",
    "discendi_santo_spirito_hino__pentecostes":"Discendi, Santo Spirito - <i>Hino - Pentecostes</i>",
    "vuestra_soy_pues_me_criasteis_s_teresa_de_avila__rafael_andreo":"Vuestra soy pues me criasteis - <i>S. Teresa de Ávila / Rafael Andreo</i>",
    "gracias_a_la_vida_violeta_parra":"Gracias a la vida - <i>Violeta Parra</i>",
    "vieni_signore_gesu_trapistas_de_vitorchiano":"Vieni, Signore Gesù - <i>Trapistas de Vitorchiano</i>",
    "liberazione_no_2_claudio_chieffo":"Liberazione nº 2 - <i>Claudio Chieffo</i>",
    "tu_mi_guardi_dalla_croce_atribuido_a_w_a_mozart":"Tu mi guardi dalla croce - <i>Atribuído a W. A. Mozart</i>",
    "meu_sao_bendito_cancao_brasileira":"Meu São Bendito - <i>Canção brasileira</i>",
    "sanctus":"Sanctus",
    "que_este_vinho_e_este_pao":"Que este vinho e este pão",
    "quem_comer_deste_pao_c_silva":"Quem comer deste pão - <i>C. Silva</i>",
    "dainos_um_coracao_a_espinosa":"Dai-nos um coração - <i>A. Espinosa</i>",
    "o_verdadeiro_corpo_do_senhor_c_silva":"Ó verdadeiro corpo do Senhor - <i>C. Silva</i>",
    "when_the_saints":"When the Saints",
    "flattire_freeway":"Flattire freeway",
    "errore_di_prospettiva_claudio_chieffo":"Errore di prospettiva - <i>Claudio Chieffo</i>",
    "al_comando_dei_nostri_ufficiali":"Al comando dei nostri ufficiali",
    "quando_uno_ha_il_cuore_buono_claudio_chieffo":"Quando uno ha il cuore buono - <i>Claudio Chieffo</i>",
    "venite_a_laudare_laudario_de_cortona_sec_xiii":"Venite a laudare - <i>Laudário de Cortona, séc. XIII</i>",
    "por_dentro_de_um_abraco_simplus":"Por dentro de um abraço - <i>Simplus</i>",
    "luz_terna":"Luz terna",
    "voume_embora_vou_partir_alentejo":"Vou-me embora, vou partir - <i>Alentejo</i>",
    "amare_ancora_claudio_chieffo":"Amare ancora - <i>Claudio Chieffo</i>",
    "over_in_the_glory_land":"Over in the glory land",
    "os_nossos_rogos_aceite":"Os nossos rogos aceite",
    "benedetto_sia_lo_giorno_g_animuccia":"Benedetto sia lo giorno - <i>G. Animuccia</i>",
    "a_procissao":"A procissão",
    "eu_ouvi_um_passarinho_baixo_alentejo":"Eu ouvi um passarinho - <i>Baixo Alentejo</i>",
    "my_father_sings_to_me_bay_ridge_band":"My Father sings to Me - <i>Bay Ridge Band</i>",
    "the_fields_on_athenry_pete_st_john":"The fields on Athenry - <i>Pete St. John</i>",
    "veni_sancte_spiritus_sequencia__pentecostes":"Veni Sancte Spiritus - <i>Sequência - Pentecostes</i>",
    "e_nossa_oferta":"É nossa oferta",
    "marta_marta_claudio_chieffo":"Marta, Marta - <i>Claudio Chieffo</i>",
    "o_designio_alberto_marani":"O Desígnio - <i>Alberto Marani</i>",
    "only_our_rivers_run_free_the_wolfe_tones":"Only our rivers run free - <i>The Wolfe Tones</i>",
    "salve_caput_cruentatum_paixao_e_morte_do_senhor":"Salve caput cruentatum - <i>Paixão e morte do Senhor</i>",
    "dulcis_christe_michelangelo_grancini_sec_xvii":"Dulcis Christe - <i>Michelangelo Grancini, séc. XVII</i>",
    "lasciati_fare_claudio_chieffo":"Lasciati fare - <i>Claudio Chieffo</i>",
    "toda_a_nossa_gloria_m_luis":"Toda a nossa glória - <i>M. Luis</i>",
    "ora_so_a_e_g_roscio_a_e_g_agape":"Ora so - <i>A. e G. Roscio, A. e G. Agape</i>",
    "deus_feznos_um_so_povo_fr_arcilio":"Deus fez-nos um só povo - <i>Fr. Arcílio</i>",
    "verei_a_bondade_do_senhor_salmo_26_j_gelineaue_bosio":"Verei a bondade do Senhor (Salmo 26) - <i>J. Gelineau/E. Bosio</i>",
    "la_ceseta_de_transaqua_canto_alpino":"La ceseta de transaqua - <i>Canto alpino</i>",
    "o_surdato_nnammurato":"O surdato ‘nnammurato",
    "ah_vinde_todos_melodia_francesa":"Ah! vinde todos - <i>Melodia francesa</i>",
    "si_dieu_ne_nous_aimait_pas_am_cocagnac_op":"Si Dieu ne nous aimait pas - <i>A.M. Cocagnac (O.P.)</i>",
    "ave_verum_sequencia":"Ave verum - <i>Sequência</i>",
    "o_cor_soave_anonimo":"O cor’ soave - <i>Anónimo</i>",
    "toma_toda_a_minha_vida":"Toma toda a minha vida",
    "matir_nieba_i_zimli":"Matir’ nieba i zimli",
    "ave_o_vergjine_canto_friulano":"Ave, o Vergjine - <i>canto friulano</i>",
    "altissima_luce_laudario_de_cortona_sec_xiii":"Altissima luce - <i>Laudário de Cortona, sec. XIII</i>",
    "fica_mal_com_deus_geraldo_vandre":"Fica mal com Deus - <i>Geraldo Vandré</i>",
    "minha_luz_maria_teresa_de_noronha":"Minha Luz - <i>Maria Teresa de Noronha</i>",
    "will_ye_go_lassie_go":"Will ye go, lassie, go?",
    "cancao_de_maria_clara_claudio_chieffo":"Canção de Maria Clara - <i>Claudio Chieffo</i>",
    "o_luar_da_meianoite_alentejo":"Ó luar da meia-noite - <i>Alentejo</i>",
    "podes_vir":"Podes vir",
    "cantiga_do_alecrim":"Cantiga do alecrim",
    "signore_delle_cime_canto_alpino":"Signore delle cime - <i>Canto Alpino</i>",
    "caminharei_alberto_marani__traducao_ritmica":"Caminharei - <i>Alberto Marani – Tradução Rítmica</i>",
    "el_vito":"El vito",
    "saboreai_e_vede_como_e_bom_o_senhor_j_gelineau":"Saboreai e vede como é bom o Senhor! - <i>J. Gelineau</i>",
    "andanca_beth_carvalho":"Andança - <i>Beth Carvalho</i>",
    "todo_cambia_mercedes_sosa":"Todo Cambia - <i>Mercedes Sosa</i>",
    "jesu_dulcis_memoria_hino__por_abadessa_beneditina_sec_xiv":"Jesu dulcis memoria - <i>Hino - por abadessa beneditina, séc. XIV</i>",
    "salve_nobre_padroeira":"Salve, nobre Padroeira",
    "barco_negro_amalia_rodrigues":"Barco Negro - <i>Amália Rodrigues</i>",
    "o_spes_mea_cara_anonimo_medieval":"O spes mea cara - <i>Anónimo medieval</i>",
    "puer_natus_anonimo_medieval":"Puer natus - <i>Anónimo medieval</i>",
    "ave_maria_luz_clara_da_manha_claudio_chieffo":"Avé Maria, luz clara da manhã - <i>Cláudio Chieffo</i>",
    "veni_creator_spiritus_hino__pentecostes":"Veni Creator Spiritus - <i>Hino - Pentecostes</i>",
    "damor_pane_dolcissimo_stefano_varnava__anonimo":"D’amor pane dolcissimo - <i>Stefano Varnavà / Anónimo</i>",
    "canzone_dellideale_claudio_chieffo":"Canzone dell’ideale - <i>Claudio chieffo</i>",
    "ave_maria_cheia_de_graca_frei_hermano_da_camara":"Avé Maria Cheia de Graça - <i>Frei. Hermano da Câmara</i>",
    "aconteceu_adriana_calcanhoto":"Aconteceu - <i>Adriana Calcanhoto</i>",
    "i_wonder":"I wonder",
    "quem_me_ensinou_a_nadar_cancao_brasileira":"Quem me ensinou a nadar - <i>Canção brasileira</i>",
    "cantai_ao_senhor_um_hino_novo_salmo_97_v_cazzaniga_j_gelineau":"Cantai ao Senhor um hino novo (Salmo 97) - <i>V Cazzaniga/ J. Gelineau</i>",
    "tantum_ergo_gregoriano":"Tantum ergo - <i>Gregoriano</i>",
    "crux_fidelis_hino__sextafeira_santa":"Crux Fidelis - <i>Hino - Sexta-Feira Santa</i>",
    "nao_quero_que_vas_a_monda":"Não quero que vás á monda",
    "exaudi_domine_lorenzo_perosi":"Exaudi Domine - <i>Lorenzo Perosi</i>",
    "nitida_stella_melodia_checa_sec_xviii":"Nitida Stella - <i>Melodia checa, séc. XVIII</i>",
    "en_que_nos_parecemos":"En que nos parecemos",
    "pavao":"Pavão",
    "ballata_del_amore_vero_claudio_chieffo":"Ballata del amore vero - <i>Claudio Chieffo</i>",
    "padre_claudio_chieffo":"Padre - <i>Claudio Chieffo</i>",
    "the_wild_rover":"The wild rover",
    "se_me_envolve_a_noite_escura":"Se me envolve a noite escura",
    "o_filii_et_filiae_tempo_pascal":"O filii et filiae - <i>Tempo Pascal</i>",
    "jesu_rex_admirabilis_pl_da_palestrina_1525__1594":"Jesu! Rex admirabilis - <i>P.L. Da Palestrina, 1525? - 1594</i>",
    "mi_prende_per_la_mano_anonimo":"Mi prende per la mano - <i>Anónimo</i>",
    "giesu_sommo_conforto":"Giesù, sommo conforto",
    "ave_maria_gregoriano":"Ave Maria - <i>Gregoriano</i>",
    "eu_te_ofereco_m_giombini":"Eu te ofereço - <i>M. Giombini</i>",
    "romagna_mia":"Romagna mia",
    "cielito_lindo":"Cielito lindo",
    "e_cantando_simplus":"É cantando - <i>Simplus</i>",
    "quais_quais_alentejo":"Quais quais - <i>Alentejo</i>",
    "angel_dal_ciel_disceso_g_ancina":"Angel dal ciel disceso - <i>G. Ancina</i>",
    "tomai_e_recebei":"Tomai e recebei",
    "ojos_de_cielo_popular_argentina":"Ojos de cielo - <i>Popular argentina</i>",
    "tu_es_um_deus_fiel":"Tu és um Deus fiel",
    "rosa_das_rosas_afonso_x_sec_xiii":"Rosa das rosas - <i>Afonso X, séc. XIII</i>",
    "alma_redemptoris_antifona__tempo_de_advento":"Alma redemptoris - <i>Antífona - Tempo de Advento</i>",
    "vamos_confiantes_salmo_45_c_silva":"Vamos confiantes (Salmo 45) - <i>C. Silva</i>",
    "a_pedra_salmo_117_adriana_mascagni":"A Pedra (Salmo 117) - <i>Adriana Mascagni</i>",
    "menina_das_trancas_pretas_m_rosario_v_camara_e_l_teixeira":"Menina das tranças pretas - <i>M. Rosário, V. Câmara e L. Teixeira</i>",
    "timoneiro_paulinho_da_viola":"Timoneiro - <i>Paulinho da Viola</i>",
    "o_bom_pastor":"O bom pastor",
    "eu_vim_para_que_tenham_vida_salmo_145_f_silva":"Eu vim para que tenham vida (Salmo 145) - <i>F. Silva</i>",
    "il_popolo_canta_la_sua_liberazione_claudio_chieffo":"Il popolo canta la sua liberazione - <i>Claudio Chieffo</i>",
    "menina_estas_a_janela_vitorino":"Menina estás à janela - <i>Vitorino</i>",
    "verdes_sao_os_campos_luis_de_camoes_jose_afonso":"Verdes são os campos - <i>Luís de Camões, José Afonso</i>",
    "tu_sei_un_dio_fedele_anonimo":"Tu sei un Dio fedele - <i>Anónimo</i>",
    "long_time_traveler_the_waillin_jennys":"Long time traveler - <i>The Waillin’ Jennys</i>",
    "a_banda_chico_buarque":"A Banda - <i>Chico Buarque</i>",
    "argento_claudio_chieffo":"Argento - <i>Claudio Chieffo</i>",
    "a_treze_de_maio":"A treze de Maio",
    "nella_tua_pace_ciro_picciano":"Nella tua pace - <i>Ciro Picciano</i>",
    "o_bone_jesu_p_da_palestrina_sec_xvi":"O bone Jesu - <i>P. da Palestrina, séc. XVI</i>",
    "il_testamento_del_capitano_canto_alpino":"Il testamento del capitano - <i>Canto alpino</i>",
    "quem_tem_sede_venha_a_mim_taize":"Quem tem sede venha a Mim - <i>Taizé</i>",
    "hino_a_sao_jose_jose_antonio_poblete":"Hino a São José - <i>José Antonio Poblete</i>",
    "vinde_a_presenca_do_senhor_salmo_99_v_cazzaniga_j_gelineau":"Vinde à presença do Senhor - <i>(Salmo 99) V. Cazzaniga, J. Gelineau</i>",
    "abandonei_a_e_g_roscio_a_e_g_agape__traducao_ritmica":"Abandonei - <i>A. e G. Roscio, A. e G. Agape - tradução ritmica</i>",
    "vinde_e_contemplai_cartageno":"Vinde e Contemplai - <i>Cartageno</i>",

};